In [1]:
import pandas as pd
DATA_DIR = r"C:\Users\HARDPC\Desktop\AL\projekty\products_prices_historical_analysis\keepa_data"

In [2]:
meta = pd.read_csv(DATA_DIR + r"\all_products_meta.csv")
meta.shape

meta.head()

,asin,title,brand,model,manufacturer,productGroup,binding,color,size,monthlySold,listedSince,trackingSince,rootCategory,parentAsin
0,B07ZPKN6YR,"Apple iPhone 11, 64GB, Black - Unlocked (Renewed)",Apple,iPhone 11,Apple Computer,Wireless,Electronics,Black,64GB,2000,4640100,4656740,2335752011,B0GR1S2JM2
1,B08PP5MSVB,"Apple iPhone 12, 64GB, Black - Fully Unlocked ...",Apple,iPhone 12,Apple Computer,Wireless,Office Product,Black,64GB,3000,5219880,5310616,2335752011,NaN
2,B09LNW3CY2,"Apple iPhone 13, 128GB, Midnight - Unlocked (R...",Apple,iPhone 13,Apple Computer,Wireless,Office Product,Midnight,128GB,3000,5713676,5804440,2335752011,B0BGQMSXYC
3,B0BN72FYFG,"Apple iPhone 14, 128GB, Midnight - Unlocked (R...",Apple,iPhone 14,Apple Computer,Wireless,NaN,Midnight,128GB,6000,6256742,6279564,2335752011,NaN
4,B0C5S83319,"Samsung Galaxy S23 5G, US Version, 128GB, Phan...",Samsung,Galaxy S23,Samsung Electronics,Wireless,Office Product,Phantom Black,128GB,500,6511502,6527170,2335752011,B0C5S9D7S7

In [3]:
meta.info()
KEEPA_EPOCH = pd.Timestamp("2011-01-01")
meta['listed_since'] = KEEPA_EPOCH + pd.to_timedelta(meta['listedSince'], unit = 'min')
meta['tracking_since'] = KEEPA_EPOCH + pd.to_timedelta(meta['trackingSince'], unit = 'min')
meta.head()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   asin           19 non-null     str
 1   title          19 non-null     str
 2   brand          19 non-null     str
 3   model          19 non-null     str
 4   manufacturer   19 non-null     str
 5   productGroup   19 non-null     str
 6   binding        13 non-null     str
 7   color          19 non-null     str
 8   size           19 non-null     str
 9   monthlySold    19 non-null     int64
 10  listedSince    19 non-null     int64
 11  trackingSince  19 non-null     int64
 12  rootCategory   19 non-null     int64
 13  parentAsin     17 non-null     str
dtypes: int64(4), str(10)
memory usage: 2.2 KB

,asin,title,brand,model,manufacturer,productGroup,binding,color,size,monthlySold,listedSince,trackingSince,rootCategory,parentAsin,listed_since,tracking_since
0,B07ZPKN6YR,"Apple iPhone 11, 64GB, Black - Unlocked (Renewed)",Apple,iPhone 11,Apple Computer,Wireless,Electronics,Black,64GB,2000,4640100,4656740,2335752011,B0GR1S2JM2,2019-10-28 07:00:00,2019-11-08 20:20:00
1,B08PP5MSVB,"Apple iPhone 12, 64GB, Black - Fully Unlocked ...",Apple,iPhone 12,Apple Computer,Wireless,Office Product,Black,64GB,3000,5219880,5310616,2335752011,NaN,2020-12-03 22:00:00,2021-02-04 22:16:00
2,B09LNW3CY2,"Apple iPhone 13, 128GB, Midnight - Unlocked (R...",Apple,iPhone 13,Apple Computer,Wireless,Office Product,Midnight,128GB,3000,5713676,5804440,2335752011,B0BGQMSXYC,2021-11-11 19:56:00,2022-01-13 20:40:00
3,B0BN72FYFG,"Apple iPhone 14, 128GB, Midnight - Unlocked (R...",Apple,iPhone 14,Apple Computer,Wireless,NaN,Midnight,128GB,6000,6256742,6279564,2335752011,NaN,2022-11-23 23:02:00,2022-12-09 19:24:00
4,B0C5S83319,"Samsung Galaxy S23 5G, US Version, 128GB, Phan...",Samsung,Galaxy S23,Samsung Electronics,Wireless,Office Product,Phantom Black,128GB,500,6511502,6527170,2335752011,B0C5S9D7S7,2023-05-19 21:02:00,2023-05-30 18:10:00

In [6]:
meta["tracking_gap_days"] = (meta["tracking_since"] - meta["listed_since"]).dt.days
meta[["asin", "brand", "model", "listed_since", "tracking_since", "tracking_gap_days"]].sort_values("tracking_gap_days", ascending=False)

,asin,brand,model,listed_since,tracking_since,tracking_gap_days
14,B09VH9BKHS,Samsung,Galaxy S22+,2022-03-14 14:02:00,2022-06-23 21:06:00,101
2,B09LNW3CY2,Apple,iPhone 13,2021-11-11 19:56:00,2022-01-13 20:40:00,63
1,B08PP5MSVB,Apple,iPhone 12,2020-12-03 22:00:00,2021-02-04 22:16:00,63
9,B0FRKS39NK,Apple,iPhone 17,2025-10-07 07:00:00,2025-11-04 07:44:00,28
15,B0BL8HPF13,Google,Pixel 7,2022-11-02 20:04:00,2022-11-29 22:34:00,27
5,B0CMPMY9ZZ,Apple,iPhone 15,2023-11-05 23:28:00,2023-11-21 06:40:00,15
3,B0BN72FYFG,Apple,iPhone 14,2022-11-23 23:02:00,2022-12-09 19:24:00,15
13,B09SYSMCX6,Google,Pixel 6,2022-02-21 04:08:00,2022-03-07 23:52:00,14
0,B07ZPKN6YR,Apple,iPhone 11,2019-10-28 07:00:00,2019-11-08 20:20:00,11
4,B0C5S83319,Samsung,Galaxy S23,2023-05-19 21:02:00,2023-05-30 18:10:00,10
6,B0D364RMMP,Samsung,Galaxy S24,2024-05-02 17:02:00,2024-05-08 00:12:00,5
12,B08VLMQ3KS,Samsung,Galaxy S21,2021-02-01 22:38:00,2021-02-07 20:40:00,5
11,B08MV7HWFK,Google,Pixel 5,2020-11-05 07:54:00,2020-11-06 18:18:00,1
7,B0DHJDPYYR,Apple,iPhone 16,2024-10-20 07:00:00,2024-10-22 03:48:00,1
10,B08L34JQ9C,Samsung,Galaxy S20 FE,2020-10-12 02:42:00,2020-10-13 07:06:00,1
16,B0CVYKL34H,Google,Pixel 8,2024-02-19 17:28:00,2024-02-21 05:50:00,1
18,B0FFTV1LXZ,Google,Pixel 10,2025-08-20 16:00:00,2025-07-30 19:36:00,-21
8,B0FG1THCD7,Samsung,Galaxy S25 FE,2025-09-04 09:30:00,2025-07-24 23:44:00,-42
17,B0DVHV7X53,Google,Pixel 9a,2025-04-10 04:00:00,2025-02-14 17:56:00,-55

In [11]:
ph = pd.read_csv(DATA_DIR + r"\B09LNW3CY2_price_history.csv")
ph.shape
ph.head(10)
ph.info


price_cols = ["AMAZON", "NEW", "USED", "LISTPRICE", "REFURBISHED"]
ph[price_cols].notna().sum()


for asin in ["B09VH9BKHS", "B0BL8HPF13"]:
    ph_tmp = pd.read_csv(DATA_DIR + f"\\{asin}_price_history.csv")
    print(asin)
    print(ph_tmp[price_cols].notna().sum())
    print()

B09VH9BKHS
AMAZON            0
NEW            2089
USED            671
LISTPRICE        24
REFURBISHED     371
dtype: int64

B0BL8HPF13
AMAZON            0
NEW            2405
USED           1206
LISTPRICE        27
REFURBISHED     587
dtype: int64